---
- name: Install metric beat
  hosts: webservers
  become: true
  tasks:
    # Use command module
  - name: Download metricbeat
    command: curl -L -O http://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb #TODO

    # Use command module
  - name: install metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb #TODO

    # Use copy module
  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml #TODO

    # Use command module
  - name: enable and configure docker module for metric beat
    command: metricbeat modules enable docker #TODO

    # Use command module
  - name: setup metric beat
    command: metricbeat setup #TODO

    # Use command module
  - name: start metric beat
    command: service metricbeat start #TODO

    # Use systemd module
  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat #TODO
      enabled: yes
